name: charcoal
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.7
    - snakemake-minimal=6.4.1
    - screed
    - click>=7,<8
    - pip
    - mamba
    - sourmash>=4.1.1,<5
