name: charcoal
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.7,<3.10
    - snakemake-minimal==6.10.0
    - screed
    - click>=7,<8
    - pip
    - mamba
    - sourmash>=4.1.1,<5
