name: charcoal
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.6
    - snakemake-minimal=5.8.1
    - screed
    - click
    - pip
    - pip:
      - sourmash==4.1.0
