name: charcoal
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.10
    - snakemake-minimal==7.32.4
    - screed
    - click>=7,<8
    - pip
    - mamba
    - sourmash==4.8.4
