name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10"]

    name: Python ${{ matrix.python }}

    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

    - name: cache conda
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: setup conda
      uses: conda-incubator/setup-miniconda@3b0f2504dd76ef23b6d31f291f4913fb60ab5ff3
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge,bioconda
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true
        mamba-version: "*"
        activate-environment: sourmash_dev
        auto-activate-base: false
        use-only-tar-bz2: true

      - name: Install coverage dependencies
        run: pip install pytest-cov pytest-dependency

#      - name: Build
#        run: python setup.py build_ext --inplace

      - name: Install charcoal
        run: pip install -e .

      - run: pytest tests

#      - run: pytest tests --cov=.

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
