name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: ["3.10"]

    name: Python ${{ matrix.python }}

    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - run: pip install -U pip setuptools

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
            activate-conda: true
      - run: conda env update -n base -f environment.yml

      - name: Install coverage dependencies
        run: pip install pytest-cov pytest-dependency

      - name: Build
        run: python setup.py build_ext --inplace

      - name: Install charcoal
        run: pip install -e .

      - run: pytest tests

#      - run: pytest tests --cov=.

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
